spring:
  profiles:
    active: ${ACTIVE_PROFILE:dev}
  output:
    ansi:
      enabled: always

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: 6379

custom:
  jwt:
    secretKey: ${JWT_SECRET}
    accessTokenExpirationSeconds: 1200   # 20분
    refreshTokenExpirationSeconds: 1209600  # 14일