services:
  postgres:
    image: postgres:16-alpine
    container_name: dabjeongneo-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      TZ: Asia/Seoul
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: dabjeongneo-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  influxdb:
    image: influxdb:1.8
    container_name: dabjeongneo-influxdb
    restart: always
    ports:
      - "8086:8086"
    volumes:
      - influxdb-data:/var/lib/influxdb

  grafana:
    image: grafana/grafana:latest
    container_name: dabjeongneo-grafana

    restart: always
    ports:
      - "3001:3000"
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    depends_on:
      - influxdb

  k6:
    image: grafana/k6:latest
    container_name: dabjeongneo-k6
    profiles: [ "loadtest" ]
    volumes:
      - ./k6/scripts:/scripts
    working_dir: /scripts
    entrypoint: [ "k6" ]


volumes:
  postgres-data:
  redis-data:
  influxdb-data:
  grafana-data: